#pragma once
#include <upcx/vm/opcodes_def.hpp>
#include <upcx/vm/variant.hpp>

#include <map>

namespace upcx { namespace vm {
   enum opcodes {
      UPCX_VM_CONTROL_FLOW_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_BR_TABLE_OP(UPCX_VM_CREATE_ENUM)
      UPCX_VM_RETURN_OP(UPCX_VM_CREATE_ENUM)
      UPCX_VM_CALL_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_CALL_IMM_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_PARAMETRIC_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_VARIABLE_ACCESS_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_MEMORY_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_I32_CONSTANT_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_I64_CONSTANT_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_F32_CONSTANT_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_F64_CONSTANT_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_COMPARISON_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_NUMERIC_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_CONVERSION_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_EXIT_OP(UPCX_VM_CREATE_ENUM)
      UPCX_VM_EMPTY_OPS(UPCX_VM_CREATE_ENUM)
      UPCX_VM_ERROR_OPS(UPCX_VM_CREATE_ENUM)
   };

   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         UPCX_VM_CONTROL_FLOW_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_BR_TABLE_OP(UPCX_VM_CREATE_MAP)
         UPCX_VM_RETURN_OP(UPCX_VM_CREATE_MAP)
         UPCX_VM_CALL_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_CALL_IMM_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_PARAMETRIC_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_VARIABLE_ACCESS_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_MEMORY_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_I32_CONSTANT_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_I64_CONSTANT_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_F32_CONSTANT_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_F64_CONSTANT_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_COMPARISON_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_NUMERIC_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_CONVERSION_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_EXIT_OP(UPCX_VM_CREATE_MAP)
         UPCX_VM_EMPTY_OPS(UPCX_VM_CREATE_MAP)
         UPCX_VM_ERROR_OPS(UPCX_VM_CREATE_MAP)
      };
   };

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   UPCX_VM_CONTROL_FLOW_OPS(UPCX_VM_CREATE_CONTROL_FLOW_TYPES)
   UPCX_VM_BR_TABLE_OP(UPCX_VM_CREATE_BR_TABLE_TYPE)
   UPCX_VM_RETURN_OP(UPCX_VM_CREATE_CONTROL_FLOW_TYPES)
   UPCX_VM_CALL_OPS(UPCX_VM_CREATE_CALL_TYPES)
   UPCX_VM_CALL_IMM_OPS(UPCX_VM_CREATE_CALL_IMM_TYPES)
   UPCX_VM_PARAMETRIC_OPS(UPCX_VM_CREATE_TYPES)
   UPCX_VM_VARIABLE_ACCESS_OPS(UPCX_VM_CREATE_VARIABLE_ACCESS_TYPES)
   UPCX_VM_MEMORY_OPS(UPCX_VM_CREATE_MEMORY_TYPES)
   UPCX_VM_I32_CONSTANT_OPS(UPCX_VM_CREATE_I32_CONSTANT_TYPE)
   UPCX_VM_I64_CONSTANT_OPS(UPCX_VM_CREATE_I64_CONSTANT_TYPE)
   UPCX_VM_F32_CONSTANT_OPS(UPCX_VM_CREATE_F32_CONSTANT_TYPE)
   UPCX_VM_F64_CONSTANT_OPS(UPCX_VM_CREATE_F64_CONSTANT_TYPE)
   UPCX_VM_COMPARISON_OPS(UPCX_VM_CREATE_TYPES)
   UPCX_VM_NUMERIC_OPS(UPCX_VM_CREATE_TYPES)
   UPCX_VM_CONVERSION_OPS(UPCX_VM_CREATE_TYPES)
   UPCX_VM_EXIT_OP(UPCX_VM_CREATE_EXIT_TYPE)
   UPCX_VM_EMPTY_OPS(UPCX_VM_CREATE_TYPES)
   UPCX_VM_ERROR_OPS(UPCX_VM_CREATE_TYPES)

   using opcode = variant<
      UPCX_VM_CONTROL_FLOW_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_BR_TABLE_OP(UPCX_VM_IDENTITY)
      UPCX_VM_RETURN_OP(UPCX_VM_IDENTITY)
      UPCX_VM_CALL_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_CALL_IMM_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_PARAMETRIC_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_VARIABLE_ACCESS_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_MEMORY_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_I32_CONSTANT_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_I64_CONSTANT_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_F32_CONSTANT_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_F64_CONSTANT_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_COMPARISON_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_NUMERIC_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_CONVERSION_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_EXIT_OP(UPCX_VM_IDENTITY)
      UPCX_VM_EMPTY_OPS(UPCX_VM_IDENTITY)
      UPCX_VM_ERROR_OPS(UPCX_VM_IDENTITY_END)
      >;
}} // namespace upcx::vm
